parameters: {}
environment: {}
packages:
  - name: ghapp
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: redirect
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        parameters: {}
        environment:
          DISCORD_WEBHOOKS: "${DISCORD_WEBHOOKS}" 
        annotations: {}
        limits: {}
