parameters: {}
environment: {}
packages:
  - name: ghapp
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: redirect
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        parameters: {}
        environment:
          # LOG_DESTINATIONS: ${LOG_DESTINATIONS}
          WEBHOOK_AM2R_DEV: "${WEBHOOK_AM2R_DEV}"
          WEBHOOK_CORRUPTION_DEV: "${WEBHOOK_CORRUPTION_DEV}"
          WEBHOOK_DREAD_DEV: "${WEBHOOK_DREAD_DEV}"
          WEBHOOK_FUSION_DEV: "${WEBHOOK_FUSION_DEV}"
          WEBHOOK_ECHOES_DEV: "${WEBHOOK_ECHOES_DEV}"
          WEBHOOK_SUPER_METROID_DEV: "${WEBHOOK_SUPER_METROID_DEV}"
          WEBHOOK_PRIME_DEV: "${WEBHOOK_PRIME_DEV}"
          WEBHOOK_RANDOVANIA_DEV: "${WEBHOOK_RANDOVANIA_DEV}"
          WEBHOOK_SAMUS_RETURNS_DEV: "${WEBHOOK_SAMUS_RETURNS_DEV}"
          WEBHOOK_CAVE_STORY_DEV: "${WEBHOOK_CAVE_STORY_DEV}"
          WEBHOOK_FACTORIO_DEV: "${WEBHOOK_FACTORIO_DEV}"
        annotations: {}
        limits: {}
